/** Автогенерация из config/gc-op-http-mapping.json — не править вручную; `node scripts/gen-gc-op-http-mapping.cjs`. */
export const GC_OP_HTTP_MAPPING_SCHEMA_VERSION = 1 as const
export type GcMappingEntry = {
  op: string
  contour: 'new' | 'legacy'
  httpMethod: 'GET' | 'POST'
  pathTemplate: string
  availability: 'enabled' | 'beta' | 'disabled' | 'unsupported'
  legacyImportAction: string | null
}
export const GC_OP_HTTP_MAPPING_ENTRIES: readonly GcMappingEntry[] = [
  { op: "setUri", contour: "new", httpMethod: "POST", pathTemplate: "/set-uri", availability: "disabled", legacyImportAction: null },
  { op: "getAllGroups", contour: "new", httpMethod: "GET", pathTemplate: "/common/get-groups", availability: "disabled", legacyImportAction: null },
  { op: "getAllPersonalManagers", contour: "new", httpMethod: "GET", pathTemplate: "/common/get-personal-managers", availability: "disabled", legacyImportAction: null },
  { op: "getTrainings", contour: "new", httpMethod: "GET", pathTemplate: "/common/get-trainings", availability: "disabled", legacyImportAction: null },
  { op: "addCommentToDeal", contour: "new", httpMethod: "POST", pathTemplate: "/deal/add-comment", availability: "disabled", legacyImportAction: null },
  { op: "addDealPositions", contour: "new", httpMethod: "POST", pathTemplate: "/deal/add-positions", availability: "disabled", legacyImportAction: null },
  { op: "getDealCalls", contour: "new", httpMethod: "GET", pathTemplate: "/deal/get-calls", availability: "disabled", legacyImportAction: null },
  { op: "getDealCancelReasons", contour: "new", httpMethod: "GET", pathTemplate: "/deal/get-cancel-reasons", availability: "disabled", legacyImportAction: null },
  { op: "getDealComments", contour: "new", httpMethod: "GET", pathTemplate: "/deal/get-comments", availability: "disabled", legacyImportAction: null },
  { op: "getDealCustomFields", contour: "new", httpMethod: "GET", pathTemplate: "/deal/get-custom-fields", availability: "disabled", legacyImportAction: null },
  { op: "getDealsTags", contour: "new", httpMethod: "GET", pathTemplate: "/deal/get-deals-tags", availability: "disabled", legacyImportAction: null },
  { op: "getDealFields", contour: "new", httpMethod: "GET", pathTemplate: "/deal/get-fields", availability: "disabled", legacyImportAction: null },
  { op: "removeDealPositions", contour: "new", httpMethod: "POST", pathTemplate: "/deal/remove-positions", availability: "disabled", legacyImportAction: null },
  { op: "updateDealFields", contour: "new", httpMethod: "POST", pathTemplate: "/deal/update-fields", availability: "disabled", legacyImportAction: null },
  { op: "addCommentToDialog", contour: "new", httpMethod: "POST", pathTemplate: "/dialog/add-comment", availability: "disabled", legacyImportAction: null },
  { op: "changeDepartment", contour: "new", httpMethod: "POST", pathTemplate: "/dialog/change-department", availability: "disabled", legacyImportAction: null },
  { op: "closeDialog", contour: "new", httpMethod: "POST", pathTemplate: "/dialog/close", availability: "disabled", legacyImportAction: null },
  { op: "getDialogHistory", contour: "new", httpMethod: "GET", pathTemplate: "/dialog/get-history", availability: "disabled", legacyImportAction: null },
  { op: "addCommentToLessonAnswer", contour: "new", httpMethod: "POST", pathTemplate: "/lesson/add-comment-to-lesson-answer", availability: "disabled", legacyImportAction: null },
  { op: "changeStatusAnswers", contour: "new", httpMethod: "POST", pathTemplate: "/lesson/change-status-answers", availability: "disabled", legacyImportAction: null },
  { op: "getLessonAnswers", contour: "new", httpMethod: "GET", pathTemplate: "/lesson/get-answers", availability: "disabled", legacyImportAction: null },
  { op: "addNote", contour: "new", httpMethod: "POST", pathTemplate: "/note/add", availability: "disabled", legacyImportAction: null },
  { op: "getOfferById", contour: "new", httpMethod: "GET", pathTemplate: "/offer/get-offer-by-id", availability: "disabled", legacyImportAction: null },
  { op: "getOffers", contour: "new", httpMethod: "GET", pathTemplate: "/offer/get-offers", availability: "disabled", legacyImportAction: null },
  { op: "getOffersTags", contour: "new", httpMethod: "GET", pathTemplate: "/offer/get-offers-tags", availability: "disabled", legacyImportAction: null },
  { op: "addUserBalance", contour: "new", httpMethod: "POST", pathTemplate: "/user/add-balance", availability: "disabled", legacyImportAction: null },
  { op: "addUserGroups", contour: "new", httpMethod: "POST", pathTemplate: "/user/add-groups", availability: "disabled", legacyImportAction: null },
  { op: "createDiploma", contour: "new", httpMethod: "POST", pathTemplate: "/user/create-diploma", availability: "disabled", legacyImportAction: null },
  { op: "getUserAnswers", contour: "new", httpMethod: "GET", pathTemplate: "/user/get-answers", availability: "disabled", legacyImportAction: null },
  { op: "getUserBalance", contour: "new", httpMethod: "GET", pathTemplate: "/user/get-balance", availability: "disabled", legacyImportAction: null },
  { op: "getUserCustomFields", contour: "new", httpMethod: "GET", pathTemplate: "/user/get-custom-fields", availability: "disabled", legacyImportAction: null },
  { op: "getUserDeals", contour: "new", httpMethod: "GET", pathTemplate: "/user/get-deals", availability: "disabled", legacyImportAction: null },
  { op: "getUserDiplomas", contour: "new", httpMethod: "GET", pathTemplate: "/user/get-diplomas", availability: "disabled", legacyImportAction: null },
  { op: "getUserFields", contour: "new", httpMethod: "GET", pathTemplate: "/user/get-fields", availability: "disabled", legacyImportAction: null },
  { op: "getUserGoalRecords", contour: "new", httpMethod: "GET", pathTemplate: "/user/get-goal-records", availability: "disabled", legacyImportAction: null },
  { op: "getUserGroups", contour: "new", httpMethod: "GET", pathTemplate: "/user/get-groups", availability: "disabled", legacyImportAction: null },
  { op: "getUserLessonAnswers", contour: "new", httpMethod: "GET", pathTemplate: "/user/get-lesson-answers", availability: "disabled", legacyImportAction: null },
  { op: "getUserPurchases", contour: "new", httpMethod: "GET", pathTemplate: "/user/get-purchases", availability: "disabled", legacyImportAction: null },
  { op: "getUserSchedule", contour: "new", httpMethod: "GET", pathTemplate: "/user/get-schedule", availability: "disabled", legacyImportAction: null },
  { op: "getUserTrainings", contour: "new", httpMethod: "GET", pathTemplate: "/user/get-trainings", availability: "disabled", legacyImportAction: null },
  { op: "getUserByTelegramChatId", contour: "new", httpMethod: "GET", pathTemplate: "/user/get-user-by-telegram-chat-id", availability: "disabled", legacyImportAction: null },
  { op: "removeUserGroups", contour: "new", httpMethod: "POST", pathTemplate: "/user/remove-groups", availability: "disabled", legacyImportAction: null },
  { op: "setUserGroups", contour: "new", httpMethod: "POST", pathTemplate: "/user/set-groups", availability: "disabled", legacyImportAction: null },
  { op: "setPersonalManager", contour: "new", httpMethod: "POST", pathTemplate: "/user/set-personal-manager", availability: "disabled", legacyImportAction: null },
  { op: "updateUserCustomFields", contour: "new", httpMethod: "POST", pathTemplate: "/user/update-custom-fields", availability: "disabled", legacyImportAction: null },
  { op: "updateUserFields", contour: "new", httpMethod: "POST", pathTemplate: "/user/update-fields", availability: "disabled", legacyImportAction: null },
  { op: "addCommentToWebinar", contour: "new", httpMethod: "POST", pathTemplate: "/webinar/add-comment", availability: "disabled", legacyImportAction: null },
  { op: "getAllWebinars", contour: "new", httpMethod: "GET", pathTemplate: "/webinar/get-all-webinars", availability: "disabled", legacyImportAction: null },
  { op: "getWebinarsByIds", contour: "new", httpMethod: "POST", pathTemplate: "/webinar/get-webinars-by-ids", availability: "disabled", legacyImportAction: null },
  { op: "moderateWebinarComment", contour: "new", httpMethod: "POST", pathTemplate: "/webinar/moderation-comment", availability: "disabled", legacyImportAction: null },
  { op: "moderateWebinarUser", contour: "new", httpMethod: "POST", pathTemplate: "/webinar/moderation-user", availability: "disabled", legacyImportAction: null },
  { op: "addUser", contour: "legacy", httpMethod: "POST", pathTemplate: "/users", availability: "enabled", legacyImportAction: "add" },
  { op: "createDeal", contour: "legacy", httpMethod: "POST", pathTemplate: "/deals", availability: "disabled", legacyImportAction: "add" },
  { op: "exportUsers", contour: "legacy", httpMethod: "GET", pathTemplate: "/account/users", availability: "disabled", legacyImportAction: null },
  { op: "exportGroupUsers", contour: "legacy", httpMethod: "GET", pathTemplate: "/account/groups/{groupId}/users", availability: "disabled", legacyImportAction: null },
  { op: "exportDeals", contour: "legacy", httpMethod: "GET", pathTemplate: "/account/deals", availability: "disabled", legacyImportAction: null },
  { op: "exportPayments", contour: "legacy", httpMethod: "GET", pathTemplate: "/account/payments", availability: "disabled", legacyImportAction: null },
  { op: "getCustomFields", contour: "legacy", httpMethod: "GET", pathTemplate: "/account/fields", availability: "disabled", legacyImportAction: null },
  { op: "getExportResult", contour: "legacy", httpMethod: "GET", pathTemplate: "/account/exports/{exportId}", availability: "disabled", legacyImportAction: null },
] as const
