// @shared
// Экспорт всех standalone-компонентов дизайн-системы
// Компоненты независимы друг от друга и не зависят от страниц

export type { FilterTab, FilterTag } from './DcSearchFilter.vue'
export type { ListItem } from './DcList.vue'
export type { TableColumn } from './DcTable.vue'
export type { CoverageTag } from './DcCoverageTags.vue'
export type { PaletteItem } from './DcPalette.vue'
export type { ChangelogItem } from './DcChangelog.vue'
export type { BarItem } from './DcBarChart.vue'
export type { QuickItem } from './DcQuickScenarios.vue'
export type { NavItem } from './DcDemoSidebar.vue'
export type { MetricTileItem } from './DcMetricTiles.vue'
export type { LineTrendPoint } from './DcLineTrendChart.vue'
export type { DonutBreakdownItem } from './DcDonutBreakdown.vue'
export type { FunnelStep } from './DcFunnelChart.vue'
export type { KanbanLabel, KanbanCard, KanbanColumn } from './DcKanbanBoard.vue'
export type { DataGridColumn, DataGridRow } from './DcDataGrid.vue'
export type { ActivityFeedItem } from './DcActivityFeed.vue'
export type { ChecklistTaskItem } from './DcChecklistBoard.vue'

export { default as AppSidebar } from './AppSidebar.vue'
export { default as DcButton } from './DcButton.vue'
export { default as DcCard } from './DcCard.vue'
export { default as DcChangelog } from './DcChangelog.vue'
export { default as DcBarChart } from './DcBarChart.vue'
export { default as DcCoverageTags } from './DcCoverageTags.vue'
export { default as DcDemoDashboard } from './DcDemoDashboard.vue'
export { default as DcDemoSidebar } from './DcDemoSidebar.vue'
export { default as DcFormField } from './DcFormField.vue'
export { default as DcGlowDots } from './DcGlowDots.vue'
export { default as DcGridLayer } from './DcGridLayer.vue'
export { default as DcHeaderActions } from './DcHeaderActions.vue'
export { default as DcHeroCard } from './DcHeroCard.vue'
export { default as DcList } from './DcList.vue'
export { default as DcLive } from './DcLive.vue'
export { default as DcModal } from './DcModal.vue'
export { default as DcMetricTiles } from './DcMetricTiles.vue'
export { default as DcNotification } from './DcNotification.vue'
export { default as DcNotificationCenter } from './DcNotificationCenter.vue'
export { default as DcDonutBreakdown } from './DcDonutBreakdown.vue'
export { default as DcFunnelChart } from './DcFunnelChart.vue'
export { default as DcDataGrid } from './DcDataGrid.vue'
export { default as DcActivityFeed } from './DcActivityFeed.vue'
export { default as DcChecklistBoard } from './DcChecklistBoard.vue'
export { default as DcKanbanBoard } from './DcKanbanBoard.vue'
export { default as DcLineTrendChart } from './DcLineTrendChart.vue'
export { default as DcPageBackground } from './DcPageBackground.vue'
export { default as DcPageHeader } from './DcPageHeader.vue'
export { default as DcPageTable } from './DcPageTable.vue'
export { default as DcPalette } from './DcPalette.vue'
export { default as DcQuickScenarios } from './DcQuickScenarios.vue'
export { default as DcSearchFilter } from './DcSearchFilter.vue'
export { default as DcState } from './DcState.vue'
export { default as DcStatCard } from './DcStatCard.vue'
export { default as DcTable } from './DcTable.vue'
export { default as DcThemeGlobalStyles } from './DcThemeGlobalStyles.vue'
